// THIS FILE IS AUTOGENERATED
// @generated
#pragma once

#include <lngs/lngs.hpp>

// clang-format off
namespace cov::app::str::errors {
    enum class lng {
        /// {0}: {1} error: {2} (Error message template; placeholder 0 will get the name of program, placeholder 1 the name of domain (such as "regex"), placeholder 2 an actual message)
        DOMAIN_ERROR_MSG = 1001,
        /// entry is not unique due to being a multivar (config_entries.c:186)
        CONFIG_NON_UNIQUE_MULTIVAR = 1002,
        /// entry is not unique due to being included (config_entries.c:191)
        CONFIG_NON_UNIQUE_INCLUDED = 1003,
        /// could not find key '{}' to delete (config_file.c:412, 442)
        CONFIG_CANNOT_DELETE = 1004,
        /// invalid config item name '{}' (config.c:1456)
        CONFIG_INVALID_NAME = 1005,
        /// HEAD refers to branch with no reports (Error message for unborn branch)
        SHOW_EMPTY_HEAD = 1006,
        /// requested object could not be found (Error message for not found)
        SHOW_NOT_FOUND = 1007,
        /// invalid pattern '{}' (Error message for invalid pattern)
        SHOW_INVALID_PATTERN = 1008,
    }; // enum class lng

    struct Resource {
        static const char* data();
        static std::size_t size();
    };

    using Strings = lngs::SingularStrings<lng, lngs::VersionedFile<1,
        lngs::storage::FileWithBuiltin<Resource>>>;
} // namespace cov::app::str::errors
// clang-format on
