#!/usr/bin/env python

import os
import sys

name = sys.argv[1]
root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
app = os.path.join(root, "libs", "app")
cov_rt = os.path.join(root, "libs", "cov-rt", "include", "cov", "app")


def touch(filename, text=None):
    print(filename)
    if text is None:
        try:
            open(filename, "r")
        except FileNotFoundError:
            open(filename, "w")
        return
    with open(filename, "w", encoding="UTF-8") as f:
        print(text, file=f)


touch(
    os.path.join(root, "data", "strings", f"{name}.lngs"),
    f"""[
    project("cov"),
    namespace("cov::app::str::{name}"),
    version("latest"),
    serial(1)
] strings {{
}}""",
)

touch(
    os.path.join(app, "include", "cov", "app", "strings", f"{name}.hh"),
    f"""// THIS FILE IS AUTOGENERATED
// @generated
#pragma once

#include <lngs/lngs.hpp>

// clang-format off
namespace cov::app::str::{name} {{
    enum class faulty {{
        UNDEFINED = 0 // File did not define any strings
    }}; // enum class faulty

    struct Resource {{
        static const char* data();
        static std::size_t size();
    }};

    using Strings = lngs::SingularStrings<faulty, lngs::VersionedFile<1,
        lngs::storage::FileWithBuiltin<Resource>>>;
}} // namespace cov::app::str::{name}
// clang-format on""",
)
touch(
    os.path.join(app, "src", "strings", f"{name}.cc"),
    f"""// THIS FILE IS AUTOGENERATED
// @generated
#include "cov/app/strings/{name}.hh"

// clang-format off
namespace cov::app::str::{name} {{
    namespace {{
        const char __resource[] = {{
            "\\x4c\\x41\\x4e\\x47\\x20\\x68\\x64\\x72\\x02\\x00\\x00\\x00\\x00\\x01\\x00\\x00"
            "\\x01\\x00\\x00\\x00\\x6c\\x61\\x73\\x74\\x00\\x00\\x00\\x00"
        }}; // __resource
    }} // namespace

    /*static*/ const char* Resource::data() {{ return __resource; }}
    /*static*/ std::size_t Resource::size() {{ return sizeof(__resource) - 1; }}
}} // namespace cov::app::str::{name}
// clang-format on""",
)
short = name
if short[:4] == "cov_":
    short = short[4:]
Short = short.capitalize()
touch(
    os.path.join(cov_rt, f"{name}_tr.hh"),
    f"""// Copyright (c) 2022 Marcin Zdun
// This code is licensed under MIT license (see LICENSE for details)

#pragma once

#include <cov/app/strings/{name}.hh>
#include <cov/app/tr.hh>

namespace cov::app {{
	using {short}lng = str::{name}::faulty;
	using {Short}Strings = str::{name}::Strings;

	template <>
	struct lngs_traits<{short}lng>
	    : base_lngs_traits<{short}lng, "{name}", {Short}Strings> {{}};
}}  // namespace cov::app""",
)
