__all__ = [
	'LANG_NEUTRAL',
	'LANG_INVARIANT',

	'LANG_AFRIKAANS',
	'LANG_ALBANIAN',
	'LANG_ALSATIAN',
	'LANG_AMHARIC',
	'LANG_ARABIC',
	'LANG_ARMENIAN',
	'LANG_ASSAMESE',
	'LANG_AZERI',
	'LANG_AZERBAIJANI',
	'LANG_BANGLA',
	'LANG_BASHKIR',
	'LANG_BASQUE',
	'LANG_BELARUSIAN',
	'LANG_BENGALI',
	'LANG_BRETON',
	'LANG_BOSNIAN',
	'LANG_BOSNIAN_NEUTRAL',
	'LANG_BULGARIAN',
	'LANG_CATALAN',
	'LANG_CENTRAL_KURDISH',
	'LANG_CHEROKEE',
	'LANG_CHINESE',
	'LANG_CHINESE_SIMPLIFIED',
	'LANG_CHINESE_TRADITIONAL',
	'LANG_CORSICAN',
	'LANG_CROATIAN',
	'LANG_CZECH',
	'LANG_DANISH',
	'LANG_DARI',
	'LANG_DIVEHI',
	'LANG_DUTCH',
	'LANG_ENGLISH',
	'LANG_ESTONIAN',
	'LANG_FAEROESE',
	'LANG_FARSI',
	'LANG_FILIPINO',
	'LANG_FINNISH',
	'LANG_FRENCH',
	'LANG_FRISIAN',
	'LANG_FULAH',
	'LANG_GALICIAN',
	'LANG_GEORGIAN',
	'LANG_GERMAN',
	'LANG_GREEK',
	'LANG_GREENLANDIC',
	'LANG_GUJARATI',
	'LANG_HAUSA',
	'LANG_HAWAIIAN',
	'LANG_HEBREW',
	'LANG_HINDI',
	'LANG_HUNGARIAN',
	'LANG_ICELANDIC',
	'LANG_IGBO',
	'LANG_INDONESIAN',
	'LANG_INUKTITUT',
	'LANG_IRISH',
	'LANG_ITALIAN',
	'LANG_JAPANESE',
	'LANG_KANNADA',
	'LANG_KASHMIRI',
	'LANG_KAZAK',
	'LANG_KHMER',
	'LANG_KICHE',
	'LANG_KINYARWANDA',
	'LANG_KONKANI',
	'LANG_KOREAN',
	'LANG_KYRGYZ',
	'LANG_LAO',
	'LANG_LATVIAN',
	'LANG_LITHUANIAN',
	'LANG_LOWER_SORBIAN',
	'LANG_LUXEMBOURGISH',
	'LANG_MACEDONIAN',
	'LANG_MALAY',
	'LANG_MALAYALAM',
	'LANG_MALTESE',
	'LANG_MANIPURI',
	'LANG_MAORI',
	'LANG_MAPUDUNGUN',
	'LANG_MARATHI',
	'LANG_MOHAWK',
	'LANG_MONGOLIAN',
	'LANG_NEPALI',
	'LANG_NORWEGIAN',
	'LANG_OCCITAN',
	'LANG_ODIA',
	'LANG_ORIYA',
	'LANG_PASHTO',
	'LANG_PERSIAN',
	'LANG_POLISH',
	'LANG_PORTUGUESE',
	'LANG_PULAR',
	'LANG_PUNJABI',
	'LANG_QUECHUA',
	'LANG_ROMANIAN',
	'LANG_ROMANSH',
	'LANG_RUSSIAN',
	'LANG_SAKHA',
	'LANG_SAMI',
	'LANG_SANSKRIT',
	'LANG_SCOTTISH_GAELIC',
	'LANG_SERBIAN',
	'LANG_SERBIAN_NEUTRAL',
	'LANG_SINDHI',
	'LANG_SINHALESE',
	'LANG_SLOVAK',
	'LANG_SLOVENIAN',
	'LANG_SOTHO',
	'LANG_SPANISH',
	'LANG_SWAHILI',
	'LANG_SWEDISH',
	'LANG_SYRIAC',
	'LANG_TAJIK',
	'LANG_TAMAZIGHT',
	'LANG_TAMIL',
	'LANG_TATAR',
	'LANG_TELUGU',
	'LANG_THAI',
	'LANG_TIBETAN',
	'LANG_TIGRIGNA',
	'LANG_TIGRINYA',
	'LANG_TSWANA',
	'LANG_TURKISH',
	'LANG_TURKMEN',
	'LANG_UIGHUR',
	'LANG_UKRAINIAN',
	'LANG_UPPER_SORBIAN',
	'LANG_URDU',
	'LANG_UZBEK',
	'LANG_VALENCIAN',
	'LANG_VIETNAMESE',
	'LANG_WELSH',
	'LANG_WOLOF',
	'LANG_XHOSA',
	'LANG_YAKUT',
	'LANG_YI',
	'LANG_YORUBA',
	'LANG_ZULU',

	'SUBLANG_NEUTRAL',
	'SUBLANG_DEFAULT',
	'SUBLANG_SYS_DEFAULT',
	'SUBLANG_CUSTOM_DEFAULT',
	'SUBLANG_CUSTOM_UNSPECIFIED',
	'SUBLANG_UI_CUSTOM_DEFAULT',

	'SUBLANG_AFRIKAANS_SOUTH_AFRICA',
	'SUBLANG_ALBANIAN_ALBANIA',
	'SUBLANG_ALSATIAN_FRANCE',
	'SUBLANG_AMHARIC_ETHIOPIA',
	'SUBLANG_ARABIC_SAUDI_ARABIA',
	'SUBLANG_ARABIC_IRAQ',
	'SUBLANG_ARABIC_EGYPT',
	'SUBLANG_ARABIC_LIBYA',
	'SUBLANG_ARABIC_ALGERIA',
	'SUBLANG_ARABIC_MOROCCO',
	'SUBLANG_ARABIC_TUNISIA',
	'SUBLANG_ARABIC_OMAN',
	'SUBLANG_ARABIC_YEMEN',
	'SUBLANG_ARABIC_SYRIA',
	'SUBLANG_ARABIC_JORDAN',
	'SUBLANG_ARABIC_LEBANON',
	'SUBLANG_ARABIC_KUWAIT',
	'SUBLANG_ARABIC_UAE',
	'SUBLANG_ARABIC_BAHRAIN',
	'SUBLANG_ARABIC_QATAR',
	'SUBLANG_ARMENIAN_ARMENIA',
	'SUBLANG_ASSAMESE_INDIA',
	'SUBLANG_AZERI_LATIN',
	'SUBLANG_AZERI_CYRILLIC',
	'SUBLANG_AZERBAIJANI_AZERBAIJAN_LATIN',
	'SUBLANG_AZERBAIJANI_AZERBAIJAN_CYRILLIC',
	'SUBLANG_BANGLA_INDIA',
	'SUBLANG_BANGLA_BANGLADESH',
	'SUBLANG_BASHKIR_RUSSIA',
	'SUBLANG_BASQUE_BASQUE',
	'SUBLANG_BELARUSIAN_BELARUS',
	'SUBLANG_BENGALI_INDIA',
	'SUBLANG_BENGALI_BANGLADESH',
	'SUBLANG_BOSNIAN_BOSNIA_HERZEGOVINA_LATIN',
	'SUBLANG_BOSNIAN_BOSNIA_HERZEGOVINA_CYRILLIC',
	'SUBLANG_BRETON_FRANCE',
	'SUBLANG_BULGARIAN_BULGARIA',
	'SUBLANG_CATALAN_CATALAN',
	'SUBLANG_CENTRAL_KURDISH_IRAQ',
	'SUBLANG_CHEROKEE_CHEROKEE',
	'SUBLANG_CHINESE_TRADITIONAL',
	'SUBLANG_CHINESE_SIMPLIFIED',
	'SUBLANG_CHINESE_HONGKONG',
	'SUBLANG_CHINESE_SINGAPORE',
	'SUBLANG_CHINESE_MACAU',
	'SUBLANG_CORSICAN_FRANCE',
	'SUBLANG_CZECH_CZECH_REPUBLIC',
	'SUBLANG_CROATIAN_CROATIA',
	'SUBLANG_CROATIAN_BOSNIA_HERZEGOVINA_LATIN',
	'SUBLANG_DANISH_DENMARK',
	'SUBLANG_DARI_AFGHANISTAN',
	'SUBLANG_DIVEHI_MALDIVES',
	'SUBLANG_DUTCH',
	'SUBLANG_DUTCH_BELGIAN',
	'SUBLANG_ENGLISH_US',
	'SUBLANG_ENGLISH_UK',
	'SUBLANG_ENGLISH_AUS',
	'SUBLANG_ENGLISH_CAN',
	'SUBLANG_ENGLISH_NZ',
	'SUBLANG_ENGLISH_EIRE',
	'SUBLANG_ENGLISH_SOUTH_AFRICA',
	'SUBLANG_ENGLISH_JAMAICA',
	'SUBLANG_ENGLISH_CARIBBEAN',
	'SUBLANG_ENGLISH_BELIZE',
	'SUBLANG_ENGLISH_TRINIDAD',
	'SUBLANG_ENGLISH_ZIMBABWE',
	'SUBLANG_ENGLISH_PHILIPPINES',
	'SUBLANG_ENGLISH_INDIA',
	'SUBLANG_ENGLISH_MALAYSIA',
	'SUBLANG_ENGLISH_SINGAPORE',
	'SUBLANG_ESTONIAN_ESTONIA',
	'SUBLANG_FAEROESE_FAROE_ISLANDS',
	'SUBLANG_FILIPINO_PHILIPPINES',
	'SUBLANG_FINNISH_FINLAND',
	'SUBLANG_FRENCH',
	'SUBLANG_FRENCH_BELGIAN',
	'SUBLANG_FRENCH_CANADIAN',
	'SUBLANG_FRENCH_SWISS',
	'SUBLANG_FRENCH_LUXEMBOURG',
	'SUBLANG_FRENCH_MONACO',
	'SUBLANG_FRISIAN_NETHERLANDS',
	'SUBLANG_FULAH_SENEGAL',
	'SUBLANG_GALICIAN_GALICIAN',
	'SUBLANG_GEORGIAN_GEORGIA',
	'SUBLANG_GERMAN',
	'SUBLANG_GERMAN_SWISS',
	'SUBLANG_GERMAN_AUSTRIAN',
	'SUBLANG_GERMAN_LUXEMBOURG',
	'SUBLANG_GERMAN_LIECHTENSTEIN',
	'SUBLANG_GREEK_GREECE',
	'SUBLANG_GREENLANDIC_GREENLAND',
	'SUBLANG_GUJARATI_INDIA',
	'SUBLANG_HAUSA_NIGERIA_LATIN',
	'SUBLANG_HAWAIIAN_US',
	'SUBLANG_HEBREW_ISRAEL',
	'SUBLANG_HINDI_INDIA',
	'SUBLANG_HUNGARIAN_HUNGARY',
	'SUBLANG_ICELANDIC_ICELAND',
	'SUBLANG_IGBO_NIGERIA',
	'SUBLANG_INDONESIAN_INDONESIA',
	'SUBLANG_INUKTITUT_CANADA',
	'SUBLANG_INUKTITUT_CANADA_LATIN',
	'SUBLANG_IRISH_IRELAND',
	'SUBLANG_ITALIAN',
	'SUBLANG_ITALIAN_SWISS',
	'SUBLANG_JAPANESE_JAPAN',
	'SUBLANG_KANNADA_INDIA',
	'SUBLANG_KASHMIRI_SASIA',
	'SUBLANG_KASHMIRI_INDIA',
	'SUBLANG_KAZAK_KAZAKHSTAN',
	'SUBLANG_KHMER_CAMBODIA',
	'SUBLANG_KICHE_GUATEMALA',
	'SUBLANG_KINYARWANDA_RWANDA',
	'SUBLANG_KONKANI_INDIA',
	'SUBLANG_KOREAN',
	'SUBLANG_KYRGYZ_KYRGYZSTAN',
	'SUBLANG_LAO_LAO',
	'SUBLANG_LATVIAN_LATVIA',
	'SUBLANG_LITHUANIAN',
	'SUBLANG_LOWER_SORBIAN_GERMANY',
	'SUBLANG_LUXEMBOURGISH_LUXEMBOURG',
	'SUBLANG_MACEDONIAN_MACEDONIA',
	'SUBLANG_MALAY_MALAYSIA',
	'SUBLANG_MALAY_BRUNEI_DARUSSALAM',
	'SUBLANG_MALAYALAM_INDIA',
	'SUBLANG_MALTESE_MALTA',
	'SUBLANG_MAORI_NEW_ZEALAND',
	'SUBLANG_MAPUDUNGUN_CHILE',
	'SUBLANG_MARATHI_INDIA',
	'SUBLANG_MOHAWK_MOHAWK',
	'SUBLANG_MONGOLIAN_CYRILLIC_MONGOLIA',
	'SUBLANG_MONGOLIAN_PRC',
	'SUBLANG_NEPALI_INDIA',
	'SUBLANG_NEPALI_NEPAL',
	'SUBLANG_NORWEGIAN_BOKMAL',
	'SUBLANG_NORWEGIAN_NYNORSK',
	'SUBLANG_OCCITAN_FRANCE',
	'SUBLANG_ODIA_INDIA',
	'SUBLANG_ORIYA_INDIA',
	'SUBLANG_PASHTO_AFGHANISTAN',
	'SUBLANG_PERSIAN_IRAN',
	'SUBLANG_POLISH_POLAND',
	'SUBLANG_PORTUGUESE',
	'SUBLANG_PORTUGUESE_BRAZILIAN',
	'SUBLANG_PULAR_SENEGAL',
	'SUBLANG_PUNJABI_INDIA',
	'SUBLANG_PUNJABI_PAKISTAN',
	'SUBLANG_QUECHUA_BOLIVIA',
	'SUBLANG_QUECHUA_ECUADOR',
	'SUBLANG_QUECHUA_PERU',
	'SUBLANG_ROMANIAN_ROMANIA',
	'SUBLANG_ROMANSH_SWITZERLAND',
	'SUBLANG_RUSSIAN_RUSSIA',
	'SUBLANG_SAKHA_RUSSIA',
	'SUBLANG_SAMI_NORTHERN_NORWAY',
	'SUBLANG_SAMI_NORTHERN_SWEDEN',
	'SUBLANG_SAMI_NORTHERN_FINLAND',
	'SUBLANG_SAMI_LULE_NORWAY',
	'SUBLANG_SAMI_LULE_SWEDEN',
	'SUBLANG_SAMI_SOUTHERN_NORWAY',
	'SUBLANG_SAMI_SOUTHERN_SWEDEN',
	'SUBLANG_SAMI_SKOLT_FINLAND',
	'SUBLANG_SAMI_INARI_FINLAND',
	'SUBLANG_SANSKRIT_INDIA',
	'SUBLANG_SCOTTISH_GAELIC',
	'SUBLANG_SERBIAN_BOSNIA_HERZEGOVINA_LATIN',
	'SUBLANG_SERBIAN_BOSNIA_HERZEGOVINA_CYRILLIC',
	'SUBLANG_SERBIAN_MONTENEGRO_LATIN',
	'SUBLANG_SERBIAN_MONTENEGRO_CYRILLIC',
	'SUBLANG_SERBIAN_SERBIA_LATIN',
	'SUBLANG_SERBIAN_SERBIA_CYRILLIC',
	'SUBLANG_SERBIAN_CROATIA',
	'SUBLANG_SERBIAN_LATIN',
	'SUBLANG_SERBIAN_CYRILLIC',
	'SUBLANG_SINDHI_INDIA',
	'SUBLANG_SINDHI_PAKISTAN',
	'SUBLANG_SINDHI_AFGHANISTAN',
	'SUBLANG_SINHALESE_SRI_LANKA',
	'SUBLANG_SOTHO_NORTHERN_SOUTH_AFRICA',
	'SUBLANG_SLOVAK_SLOVAKIA',
	'SUBLANG_SLOVENIAN_SLOVENIA',
	'SUBLANG_SPANISH',
	'SUBLANG_SPANISH_MEXICAN',
	'SUBLANG_SPANISH_MODERN',
	'SUBLANG_SPANISH_GUATEMALA',
	'SUBLANG_SPANISH_COSTA_RICA',
	'SUBLANG_SPANISH_PANAMA',
	'SUBLANG_SPANISH_DOMINICAN_REPUBLIC',
	'SUBLANG_SPANISH_VENEZUELA',
	'SUBLANG_SPANISH_COLOMBIA',
	'SUBLANG_SPANISH_PERU',
	'SUBLANG_SPANISH_ARGENTINA',
	'SUBLANG_SPANISH_ECUADOR',
	'SUBLANG_SPANISH_CHILE',
	'SUBLANG_SPANISH_URUGUAY',
	'SUBLANG_SPANISH_PARAGUAY',
	'SUBLANG_SPANISH_BOLIVIA',
	'SUBLANG_SPANISH_EL_SALVADOR',
	'SUBLANG_SPANISH_HONDURAS',
	'SUBLANG_SPANISH_NICARAGUA',
	'SUBLANG_SPANISH_PUERTO_RICO',
	'SUBLANG_SPANISH_US',
	'SUBLANG_SWAHILI_KENYA',
	'SUBLANG_SWEDISH',
	'SUBLANG_SWEDISH_FINLAND',
	'SUBLANG_SYRIAC_SYRIA',
	'SUBLANG_TAJIK_TAJIKISTAN',
	'SUBLANG_TAMAZIGHT_ALGERIA_LATIN',
	'SUBLANG_TAMAZIGHT_MOROCCO_TIFINAGH',
	'SUBLANG_TAMIL_INDIA',
	'SUBLANG_TAMIL_SRI_LANKA',
	'SUBLANG_TATAR_RUSSIA',
	'SUBLANG_TELUGU_INDIA',
	'SUBLANG_THAI_THAILAND',
	'SUBLANG_TIBETAN_PRC',
	'SUBLANG_TIGRIGNA_ERITREA',
	'SUBLANG_TIGRINYA_ERITREA',
	'SUBLANG_TIGRINYA_ETHIOPIA',
	'SUBLANG_TSWANA_BOTSWANA',
	'SUBLANG_TSWANA_SOUTH_AFRICA',
	'SUBLANG_TURKISH_TURKEY',
	'SUBLANG_TURKMEN_TURKMENISTAN',
	'SUBLANG_UIGHUR_PRC',
	'SUBLANG_UKRAINIAN_UKRAINE',
	'SUBLANG_UPPER_SORBIAN_GERMANY',
	'SUBLANG_URDU_PAKISTAN',
	'SUBLANG_URDU_INDIA',
	'SUBLANG_UZBEK_LATIN',
	'SUBLANG_UZBEK_CYRILLIC',
	'SUBLANG_VALENCIAN_VALENCIA',
	'SUBLANG_VIETNAMESE_VIETNAM',
	'SUBLANG_WELSH_UNITED_KINGDOM',
	'SUBLANG_WOLOF_SENEGAL',
	'SUBLANG_XHOSA_SOUTH_AFRICA',
	'SUBLANG_YAKUT_RUSSIA',
	'SUBLANG_YI_PRC',
	'SUBLANG_YORUBA_NIGERIA',
	'SUBLANG_ZULU_SOUTH_AFRICA',
]

# Picked up from winnt.h
LANG_NEUTRAL                     = 0x00
LANG_INVARIANT                   = 0x7f

LANG_AFRIKAANS                   = 0x36
LANG_ALBANIAN                    = 0x1c
LANG_ALSATIAN                    = 0x84
LANG_AMHARIC                     = 0x5e
LANG_ARABIC                      = 0x01
LANG_ARMENIAN                    = 0x2b
LANG_ASSAMESE                    = 0x4d
LANG_AZERI                       = 0x2c
LANG_AZERBAIJANI                 = 0x2c
LANG_BANGLA                      = 0x45
LANG_BASHKIR                     = 0x6d
LANG_BASQUE                      = 0x2d
LANG_BELARUSIAN                  = 0x23
LANG_BENGALI                     = 0x45
LANG_BRETON                      = 0x7e
LANG_BOSNIAN                     = 0x1a
LANG_BOSNIAN_NEUTRAL           = 0x781a
LANG_BULGARIAN                   = 0x02
LANG_CATALAN                     = 0x03
LANG_CENTRAL_KURDISH             = 0x92
LANG_CHEROKEE                    = 0x5c
LANG_CHINESE                     = 0x04
LANG_CHINESE_SIMPLIFIED          = 0x04
LANG_CHINESE_TRADITIONAL       = 0x7c04
LANG_CORSICAN                    = 0x83
LANG_CROATIAN                    = 0x1a
LANG_CZECH                       = 0x05
LANG_DANISH                      = 0x06
LANG_DARI                        = 0x8c
LANG_DIVEHI                      = 0x65
LANG_DUTCH                       = 0x13
LANG_ENGLISH                     = 0x09
LANG_ESTONIAN                    = 0x25
LANG_FAEROESE                    = 0x38
LANG_FARSI                       = 0x29
LANG_FILIPINO                    = 0x64
LANG_FINNISH                     = 0x0b
LANG_FRENCH                      = 0x0c
LANG_FRISIAN                     = 0x62
LANG_FULAH                       = 0x67
LANG_GALICIAN                    = 0x56
LANG_GEORGIAN                    = 0x37
LANG_GERMAN                      = 0x07
LANG_GREEK                       = 0x08
LANG_GREENLANDIC                 = 0x6f
LANG_GUJARATI                    = 0x47
LANG_HAUSA                       = 0x68
LANG_HAWAIIAN                    = 0x75
LANG_HEBREW                      = 0x0d
LANG_HINDI                       = 0x39
LANG_HUNGARIAN                   = 0x0e
LANG_ICELANDIC                   = 0x0f
LANG_IGBO                        = 0x70
LANG_INDONESIAN                  = 0x21
LANG_INUKTITUT                   = 0x5d
LANG_IRISH                       = 0x3c
LANG_ITALIAN                     = 0x10
LANG_JAPANESE                    = 0x11
LANG_KANNADA                     = 0x4b
LANG_KASHMIRI                    = 0x60
LANG_KAZAK                       = 0x3f
LANG_KHMER                       = 0x53
LANG_KICHE                       = 0x86
LANG_KINYARWANDA                 = 0x87
LANG_KONKANI                     = 0x57
LANG_KOREAN                      = 0x12
LANG_KYRGYZ                      = 0x40
LANG_LAO                         = 0x54
LANG_LATVIAN                     = 0x26
LANG_LITHUANIAN                  = 0x27
LANG_LOWER_SORBIAN               = 0x2e
LANG_LUXEMBOURGISH               = 0x6e
LANG_MACEDONIAN                  = 0x2f
LANG_MALAY                       = 0x3e
LANG_MALAYALAM                   = 0x4c
LANG_MALTESE                     = 0x3a
LANG_MANIPURI                    = 0x58
LANG_MAORI                       = 0x81
LANG_MAPUDUNGUN                  = 0x7a
LANG_MARATHI                     = 0x4e
LANG_MOHAWK                      = 0x7c
LANG_MONGOLIAN                   = 0x50
LANG_NEPALI                      = 0x61
LANG_NORWEGIAN                   = 0x14
LANG_OCCITAN                     = 0x82
LANG_ODIA                        = 0x48
LANG_ORIYA                       = 0x48
LANG_PASHTO                      = 0x63
LANG_PERSIAN                     = 0x29
LANG_POLISH                      = 0x15
LANG_PORTUGUESE                  = 0x16
LANG_PULAR                       = 0x67
LANG_PUNJABI                     = 0x46
LANG_QUECHUA                     = 0x6b
LANG_ROMANIAN                    = 0x18
LANG_ROMANSH                     = 0x17
LANG_RUSSIAN                     = 0x19
LANG_SAKHA                       = 0x85
LANG_SAMI                        = 0x3b
LANG_SANSKRIT                    = 0x4f
LANG_SCOTTISH_GAELIC             = 0x91
LANG_SERBIAN                     = 0x1a
LANG_SERBIAN_NEUTRAL           = 0x7c1a
LANG_SINDHI                      = 0x59
LANG_SINHALESE                   = 0x5b
LANG_SLOVAK                      = 0x1b
LANG_SLOVENIAN                   = 0x24
LANG_SOTHO                       = 0x6c
LANG_SPANISH                     = 0x0a
LANG_SWAHILI                     = 0x41
LANG_SWEDISH                     = 0x1d
LANG_SYRIAC                      = 0x5a
LANG_TAJIK                       = 0x28
LANG_TAMAZIGHT                   = 0x5f
LANG_TAMIL                       = 0x49
LANG_TATAR                       = 0x44
LANG_TELUGU                      = 0x4a
LANG_THAI                        = 0x1e
LANG_TIBETAN                     = 0x51
LANG_TIGRIGNA                    = 0x73
LANG_TIGRINYA                    = 0x73
LANG_TSWANA                      = 0x32
LANG_TURKISH                     = 0x1f
LANG_TURKMEN                     = 0x42
LANG_UIGHUR                      = 0x80
LANG_UKRAINIAN                   = 0x22
LANG_UPPER_SORBIAN               = 0x2e
LANG_URDU                        = 0x20
LANG_UZBEK                       = 0x43
LANG_VALENCIAN                   = 0x03
LANG_VIETNAMESE                  = 0x2a
LANG_WELSH                       = 0x52
LANG_WOLOF                       = 0x88
LANG_XHOSA                       = 0x34
LANG_YAKUT                       = 0x85
LANG_YI                          = 0x78
LANG_YORUBA                      = 0x6a
LANG_ZULU                        = 0x35

SUBLANG_NEUTRAL                             = 0x00
SUBLANG_DEFAULT                             = 0x01
SUBLANG_SYS_DEFAULT                         = 0x02
SUBLANG_CUSTOM_DEFAULT                      = 0x03
SUBLANG_CUSTOM_UNSPECIFIED                  = 0x04
SUBLANG_UI_CUSTOM_DEFAULT                   = 0x05

SUBLANG_AFRIKAANS_SOUTH_AFRICA              = 0x01
SUBLANG_ALBANIAN_ALBANIA                    = 0x01
SUBLANG_ALSATIAN_FRANCE                     = 0x01
SUBLANG_AMHARIC_ETHIOPIA                    = 0x01
SUBLANG_ARABIC_SAUDI_ARABIA                 = 0x01
SUBLANG_ARABIC_IRAQ                         = 0x02
SUBLANG_ARABIC_EGYPT                        = 0x03
SUBLANG_ARABIC_LIBYA                        = 0x04
SUBLANG_ARABIC_ALGERIA                      = 0x05
SUBLANG_ARABIC_MOROCCO                      = 0x06
SUBLANG_ARABIC_TUNISIA                      = 0x07
SUBLANG_ARABIC_OMAN                         = 0x08
SUBLANG_ARABIC_YEMEN                        = 0x09
SUBLANG_ARABIC_SYRIA                        = 0x0a
SUBLANG_ARABIC_JORDAN                       = 0x0b
SUBLANG_ARABIC_LEBANON                      = 0x0c
SUBLANG_ARABIC_KUWAIT                       = 0x0d
SUBLANG_ARABIC_UAE                          = 0x0e
SUBLANG_ARABIC_BAHRAIN                      = 0x0f
SUBLANG_ARABIC_QATAR                        = 0x10
SUBLANG_ARMENIAN_ARMENIA                    = 0x01
SUBLANG_ASSAMESE_INDIA                      = 0x01
SUBLANG_AZERI_LATIN                         = 0x01
SUBLANG_AZERI_CYRILLIC                      = 0x02
SUBLANG_AZERBAIJANI_AZERBAIJAN_LATIN        = 0x01
SUBLANG_AZERBAIJANI_AZERBAIJAN_CYRILLIC     = 0x02
SUBLANG_BANGLA_INDIA                        = 0x01
SUBLANG_BANGLA_BANGLADESH                   = 0x02
SUBLANG_BASHKIR_RUSSIA                      = 0x01
SUBLANG_BASQUE_BASQUE                       = 0x01
SUBLANG_BELARUSIAN_BELARUS                  = 0x01
SUBLANG_BENGALI_INDIA                       = 0x01
SUBLANG_BENGALI_BANGLADESH                  = 0x02
SUBLANG_BOSNIAN_BOSNIA_HERZEGOVINA_LATIN    = 0x05
SUBLANG_BOSNIAN_BOSNIA_HERZEGOVINA_CYRILLIC = 0x08
SUBLANG_BRETON_FRANCE                       = 0x01
SUBLANG_BULGARIAN_BULGARIA                  = 0x01
SUBLANG_CATALAN_CATALAN                     = 0x01
SUBLANG_CENTRAL_KURDISH_IRAQ                = 0x01
SUBLANG_CHEROKEE_CHEROKEE                   = 0x01
SUBLANG_CHINESE_TRADITIONAL                 = 0x01
SUBLANG_CHINESE_SIMPLIFIED                  = 0x02
SUBLANG_CHINESE_HONGKONG                    = 0x03
SUBLANG_CHINESE_SINGAPORE                   = 0x04
SUBLANG_CHINESE_MACAU                       = 0x05
SUBLANG_CORSICAN_FRANCE                     = 0x01
SUBLANG_CZECH_CZECH_REPUBLIC                = 0x01
SUBLANG_CROATIAN_CROATIA                    = 0x01
SUBLANG_CROATIAN_BOSNIA_HERZEGOVINA_LATIN   = 0x04
SUBLANG_DANISH_DENMARK                      = 0x01
SUBLANG_DARI_AFGHANISTAN                    = 0x01
SUBLANG_DIVEHI_MALDIVES                     = 0x01
SUBLANG_DUTCH                               = 0x01
SUBLANG_DUTCH_BELGIAN                       = 0x02
SUBLANG_ENGLISH_US                          = 0x01
SUBLANG_ENGLISH_UK                          = 0x02
SUBLANG_ENGLISH_AUS                         = 0x03
SUBLANG_ENGLISH_CAN                         = 0x04
SUBLANG_ENGLISH_NZ                          = 0x05
SUBLANG_ENGLISH_EIRE                        = 0x06
SUBLANG_ENGLISH_SOUTH_AFRICA                = 0x07
SUBLANG_ENGLISH_JAMAICA                     = 0x08
SUBLANG_ENGLISH_CARIBBEAN                   = 0x09
SUBLANG_ENGLISH_BELIZE                      = 0x0a
SUBLANG_ENGLISH_TRINIDAD                    = 0x0b
SUBLANG_ENGLISH_ZIMBABWE                    = 0x0c
SUBLANG_ENGLISH_PHILIPPINES                 = 0x0d
SUBLANG_ENGLISH_INDIA                       = 0x10
SUBLANG_ENGLISH_MALAYSIA                    = 0x11
SUBLANG_ENGLISH_SINGAPORE                   = 0x12
SUBLANG_ESTONIAN_ESTONIA                    = 0x01
SUBLANG_FAEROESE_FAROE_ISLANDS              = 0x01
SUBLANG_FILIPINO_PHILIPPINES                = 0x01
SUBLANG_FINNISH_FINLAND                     = 0x01
SUBLANG_FRENCH                              = 0x01
SUBLANG_FRENCH_BELGIAN                      = 0x02
SUBLANG_FRENCH_CANADIAN                     = 0x03
SUBLANG_FRENCH_SWISS                        = 0x04
SUBLANG_FRENCH_LUXEMBOURG                   = 0x05
SUBLANG_FRENCH_MONACO                       = 0x06
SUBLANG_FRISIAN_NETHERLANDS                 = 0x01
SUBLANG_FULAH_SENEGAL                       = 0x02
SUBLANG_GALICIAN_GALICIAN                   = 0x01
SUBLANG_GEORGIAN_GEORGIA                    = 0x01
SUBLANG_GERMAN                              = 0x01
SUBLANG_GERMAN_SWISS                        = 0x02
SUBLANG_GERMAN_AUSTRIAN                     = 0x03
SUBLANG_GERMAN_LUXEMBOURG                   = 0x04
SUBLANG_GERMAN_LIECHTENSTEIN                = 0x05
SUBLANG_GREEK_GREECE                        = 0x01
SUBLANG_GREENLANDIC_GREENLAND               = 0x01
SUBLANG_GUJARATI_INDIA                      = 0x01
SUBLANG_HAUSA_NIGERIA_LATIN                 = 0x01
SUBLANG_HAWAIIAN_US                         = 0x01
SUBLANG_HEBREW_ISRAEL                       = 0x01
SUBLANG_HINDI_INDIA                         = 0x01
SUBLANG_HUNGARIAN_HUNGARY                   = 0x01
SUBLANG_ICELANDIC_ICELAND                   = 0x01
SUBLANG_IGBO_NIGERIA                        = 0x01
SUBLANG_INDONESIAN_INDONESIA                = 0x01
SUBLANG_INUKTITUT_CANADA                    = 0x01
SUBLANG_INUKTITUT_CANADA_LATIN              = 0x02
SUBLANG_IRISH_IRELAND                       = 0x02
SUBLANG_ITALIAN                             = 0x01
SUBLANG_ITALIAN_SWISS                       = 0x02
SUBLANG_JAPANESE_JAPAN                      = 0x01
SUBLANG_KANNADA_INDIA                       = 0x01
SUBLANG_KASHMIRI_SASIA                      = 0x02
SUBLANG_KASHMIRI_INDIA                      = 0x02
SUBLANG_KAZAK_KAZAKHSTAN                    = 0x01
SUBLANG_KHMER_CAMBODIA                      = 0x01
SUBLANG_KICHE_GUATEMALA                     = 0x01
SUBLANG_KINYARWANDA_RWANDA                  = 0x01
SUBLANG_KONKANI_INDIA                       = 0x01
SUBLANG_KOREAN                              = 0x01
SUBLANG_KYRGYZ_KYRGYZSTAN                   = 0x01
SUBLANG_LAO_LAO                             = 0x01
SUBLANG_LATVIAN_LATVIA                      = 0x01
SUBLANG_LITHUANIAN                          = 0x01
SUBLANG_LOWER_SORBIAN_GERMANY               = 0x02
SUBLANG_LUXEMBOURGISH_LUXEMBOURG            = 0x01
SUBLANG_MACEDONIAN_MACEDONIA                = 0x01
SUBLANG_MALAY_MALAYSIA                      = 0x01
SUBLANG_MALAY_BRUNEI_DARUSSALAM             = 0x02
SUBLANG_MALAYALAM_INDIA                     = 0x01
SUBLANG_MALTESE_MALTA                       = 0x01
SUBLANG_MAORI_NEW_ZEALAND                   = 0x01
SUBLANG_MAPUDUNGUN_CHILE                    = 0x01
SUBLANG_MARATHI_INDIA                       = 0x01
SUBLANG_MOHAWK_MOHAWK                       = 0x01
SUBLANG_MONGOLIAN_CYRILLIC_MONGOLIA         = 0x01
SUBLANG_MONGOLIAN_PRC                       = 0x02
SUBLANG_NEPALI_INDIA                        = 0x02
SUBLANG_NEPALI_NEPAL                        = 0x01
SUBLANG_NORWEGIAN_BOKMAL                    = 0x01
SUBLANG_NORWEGIAN_NYNORSK                   = 0x02
SUBLANG_OCCITAN_FRANCE                      = 0x01
SUBLANG_ODIA_INDIA                          = 0x01
SUBLANG_ORIYA_INDIA                         = 0x01
SUBLANG_PASHTO_AFGHANISTAN                  = 0x01
SUBLANG_PERSIAN_IRAN                        = 0x01
SUBLANG_POLISH_POLAND                       = 0x01
SUBLANG_PORTUGUESE                          = 0x02
SUBLANG_PORTUGUESE_BRAZILIAN                = 0x01
SUBLANG_PULAR_SENEGAL                       = 0x02
SUBLANG_PUNJABI_INDIA                       = 0x01
SUBLANG_PUNJABI_PAKISTAN                    = 0x02
SUBLANG_QUECHUA_BOLIVIA                     = 0x01
SUBLANG_QUECHUA_ECUADOR                     = 0x02
SUBLANG_QUECHUA_PERU                        = 0x03
SUBLANG_ROMANIAN_ROMANIA                    = 0x01
SUBLANG_ROMANSH_SWITZERLAND                 = 0x01
SUBLANG_RUSSIAN_RUSSIA                      = 0x01
SUBLANG_SAKHA_RUSSIA                        = 0x01
SUBLANG_SAMI_NORTHERN_NORWAY                = 0x01
SUBLANG_SAMI_NORTHERN_SWEDEN                = 0x02
SUBLANG_SAMI_NORTHERN_FINLAND               = 0x03
SUBLANG_SAMI_LULE_NORWAY                    = 0x04
SUBLANG_SAMI_LULE_SWEDEN                    = 0x05
SUBLANG_SAMI_SOUTHERN_NORWAY                = 0x06
SUBLANG_SAMI_SOUTHERN_SWEDEN                = 0x07
SUBLANG_SAMI_SKOLT_FINLAND                  = 0x08
SUBLANG_SAMI_INARI_FINLAND                  = 0x09
SUBLANG_SANSKRIT_INDIA                      = 0x01
SUBLANG_SCOTTISH_GAELIC                     = 0x01
SUBLANG_SERBIAN_BOSNIA_HERZEGOVINA_LATIN    = 0x06
SUBLANG_SERBIAN_BOSNIA_HERZEGOVINA_CYRILLIC = 0x07
SUBLANG_SERBIAN_MONTENEGRO_LATIN            = 0x0b
SUBLANG_SERBIAN_MONTENEGRO_CYRILLIC         = 0x0c
SUBLANG_SERBIAN_SERBIA_LATIN                = 0x09
SUBLANG_SERBIAN_SERBIA_CYRILLIC             = 0x0a
SUBLANG_SERBIAN_CROATIA                     = 0x01
SUBLANG_SERBIAN_LATIN                       = 0x02
SUBLANG_SERBIAN_CYRILLIC                    = 0x03
SUBLANG_SINDHI_INDIA                        = 0x01
SUBLANG_SINDHI_PAKISTAN                     = 0x02
SUBLANG_SINDHI_AFGHANISTAN                  = 0x02
SUBLANG_SINHALESE_SRI_LANKA                 = 0x01
SUBLANG_SOTHO_NORTHERN_SOUTH_AFRICA         = 0x01
SUBLANG_SLOVAK_SLOVAKIA                     = 0x01
SUBLANG_SLOVENIAN_SLOVENIA                  = 0x01
SUBLANG_SPANISH                             = 0x01
SUBLANG_SPANISH_MEXICAN                     = 0x02
SUBLANG_SPANISH_MODERN                      = 0x03
SUBLANG_SPANISH_GUATEMALA                   = 0x04
SUBLANG_SPANISH_COSTA_RICA                  = 0x05
SUBLANG_SPANISH_PANAMA                      = 0x06
SUBLANG_SPANISH_DOMINICAN_REPUBLIC          = 0x07
SUBLANG_SPANISH_VENEZUELA                   = 0x08
SUBLANG_SPANISH_COLOMBIA                    = 0x09
SUBLANG_SPANISH_PERU                        = 0x0a
SUBLANG_SPANISH_ARGENTINA                   = 0x0b
SUBLANG_SPANISH_ECUADOR                     = 0x0c
SUBLANG_SPANISH_CHILE                       = 0x0d
SUBLANG_SPANISH_URUGUAY                     = 0x0e
SUBLANG_SPANISH_PARAGUAY                    = 0x0f
SUBLANG_SPANISH_BOLIVIA                     = 0x10
SUBLANG_SPANISH_EL_SALVADOR                 = 0x11
SUBLANG_SPANISH_HONDURAS                    = 0x12
SUBLANG_SPANISH_NICARAGUA                   = 0x13
SUBLANG_SPANISH_PUERTO_RICO                 = 0x14
SUBLANG_SPANISH_US                          = 0x15
SUBLANG_SWAHILI_KENYA                       = 0x01
SUBLANG_SWEDISH                             = 0x01
SUBLANG_SWEDISH_FINLAND                     = 0x02
SUBLANG_SYRIAC_SYRIA                        = 0x01
SUBLANG_TAJIK_TAJIKISTAN                    = 0x01
SUBLANG_TAMAZIGHT_ALGERIA_LATIN             = 0x02
SUBLANG_TAMAZIGHT_MOROCCO_TIFINAGH          = 0x04
SUBLANG_TAMIL_INDIA                         = 0x01
SUBLANG_TAMIL_SRI_LANKA                     = 0x02
SUBLANG_TATAR_RUSSIA                        = 0x01
SUBLANG_TELUGU_INDIA                        = 0x01
SUBLANG_THAI_THAILAND                       = 0x01
SUBLANG_TIBETAN_PRC                         = 0x01
SUBLANG_TIGRIGNA_ERITREA                    = 0x02
SUBLANG_TIGRINYA_ERITREA                    = 0x02
SUBLANG_TIGRINYA_ETHIOPIA                   = 0x01
SUBLANG_TSWANA_BOTSWANA                     = 0x02
SUBLANG_TSWANA_SOUTH_AFRICA                 = 0x01
SUBLANG_TURKISH_TURKEY                      = 0x01
SUBLANG_TURKMEN_TURKMENISTAN                = 0x01
SUBLANG_UIGHUR_PRC                          = 0x01
SUBLANG_UKRAINIAN_UKRAINE                   = 0x01
SUBLANG_UPPER_SORBIAN_GERMANY               = 0x01
SUBLANG_URDU_PAKISTAN                       = 0x01
SUBLANG_URDU_INDIA                          = 0x02
SUBLANG_UZBEK_LATIN                         = 0x01
SUBLANG_UZBEK_CYRILLIC                      = 0x02
SUBLANG_VALENCIAN_VALENCIA                  = 0x02
SUBLANG_VIETNAMESE_VIETNAM                  = 0x01
SUBLANG_WELSH_UNITED_KINGDOM                = 0x01
SUBLANG_WOLOF_SENEGAL                       = 0x01
SUBLANG_XHOSA_SOUTH_AFRICA                  = 0x01
SUBLANG_YAKUT_RUSSIA                        = 0x01
SUBLANG_YI_PRC                              = 0x01
SUBLANG_YORUBA_NIGERIA                      = 0x01
SUBLANG_ZULU_SOUTH_AFRICA                   = 0x01
