// THIS FILE IS AUTOGENERATED
// @generated
#include "cov/app/strings/cov_report.hh"

// clang-format off
namespace cov::app::str::cov_report {
    namespace {
        const char __resource[] = {
            "\x4c\x41\x4e\x47\x20\x68\x64\x72\x02\x00\x00\x00\x00\x01\x00\x00"
            "\x01\x00\x00\x00\x6c\x61\x73\x74\x00\x00\x00\x00"
        }; // __resource
    } // namespace

    /*static*/ const char* Resource::data() { return __resource; }
    /*static*/ std::size_t Resource::size() { return sizeof(__resource) - 1; }
} // namespace cov::app::str::cov_report
// clang-format on
