set(__content "// Copyright (c) 2022 Marcin Zdun
// This code is licensed under MIT license (see LICENSE for details)
// This file was autogenerated. Do not edit.

#pragma once
#include <cov/app/tools.hh>

namespace cov::app::builtin {
\tusing namespace std::literals\;

")

foreach(NAME ${BUILTINS})
    string(REPLACE "-" "_" SAFE_NAME "${NAME}")
    string(APPEND __content "\tnamespace ${SAFE_NAME} {
\t\tint handle(std::string_view tool, args::arglist args)\;
\t}
")
endforeach()

string(APPEND __content "
\tstatic constexpr app::builtin_tool tools[] = {
")

foreach(NAME ${BUILTINS})
    string(REPLACE "-" "_" SAFE_NAME "${NAME}")
    string(APPEND __content "\t    {\"${NAME}\"sv, ${SAFE_NAME}::handle},
")
endforeach()

string(APPEND __content "\t}\;
}  // namespace cov::app::builtin
")


file(GENERATE
    OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/gen/cov/builtins.hh
    CONTENT ${__content}
)
